### ISSUE TITLE
Documentation isn't that helpful :(

### ISSUE THREAD

**Issue by piegamesde** [thehottgame/TheHoTTGame#13]
I hate to break it to you, because you've written a lot of documentation and it genuinely isn't that helpful at the moment. But I think this can be fixed:

- For whom is the documentation written? Most applications distinguish between "users", "developers" (and sometimes "downstream package maintainers"). For example, as a user, I just want to get a binary and run it. I don't really care about your Emacs setup.
- I really like Nix, but unless this is the primary supported installation method you may want to reconsider whether you want to clutter the documentation of an installation of Nix itself. Maybe pull it out like the "Getting Git on MacOS"?
- The document should be accessible from the navigation. For example, I wouldn't expect the "Test it" header to mean "Test your agda development setup". More generally, headers should be self-contained and not reference previous headers that are on the same level.
- I am missing the instructions how to actually build the final binary or how to run the project.
- There should be a path towards building the application that does not involve any text editors.

**Comment by Jlh18** [comment]
Hi there, and thanks for the feedback.

- I suppose this documentation is for users, but specifically it is intended for mathematicians that have absolutely no experience installing things themselves (which was me when I started this project). 
- I believe that the emacs + some text editor setup is important for the user experience because agda is designed to be used with the interactive holes (this is "agda mode"). I don't want to suggest on the website that simply compiling the code and then going back to the file to modify it is the way it was intended to be used, with the target audience in mind. To be honest I haven't even thought about doing things the way you suggest and I expect anyone who knows better than myself should be able to read the official documentation provided for agda. If you feel strongly that we should have such a section on just running a binary, feel free to add this yourself, because that would be much better than me trying to figure out what you want and failing to implement it.
- You're right about the Nix stuff taking up valuable space, and I think I'll move it out as you suggest. The reason I include it is because installing everything directly on Windows is quite a painful experience, so I thought a detailed guide to circumvent that was a good idea.
- I also agree on your point about the "test it" section

**Comment by piegamesde** [comment]
Okay. I think I had a fundamental misconception what this whole project is. I thought it was some binary one could execute in the end, but it rather seems to be a library and the main interaction is through a code editor and compiler?

**Comment by Jlh18** [comment]
Right, this library consists of partially complete agda code - exercises for the guides on the website. The intended use for agda is via interaction through an editor that supports `agda mode` (which relies on emacs), but I think agda can be installed without this, and one could just compile the code from a terminal and edit the documents directly (as I thought you were suggesting)
